name: filex
description: A new Flutter application.
publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2 
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons.git
  percent_indicator: ^4.2.2
  mime_type: ^1.0.0
  shared_preferences:
    git: https://github.com/kumsumit/shared_preferences.git
  device_info_plus:
    git: https://github.com/kumsumit/device_info_plus.git
  path: ^1.9.0
#  thumbnails: ^1.0.1
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  cherry_toast: ^1.10.0
  permission_handler:
    git: https://github.com/kumsumit/permission_handler.git
  intl: ^0.19.0
  open_filex: ^4.4.0
  device_apps:
    git: https://github.com/sumitsharansatsangi/flutter_plugin_device_apps.git
  share_plus:
    git: https://github.com/kumsumit/share_plus.git
  video_player:
    git: https://github.com/kumsumit/video_player.git  
  isolate_handler:
    git: https://github.com/sumitsharansatsangi/isolate_handler.git
# dependency_overrides:
  platform: ^3.1.4
  file: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
