name: filex
description: A new Flutter application.
publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons.git
  isolate_handler:
    git: https://github.com/sumitsharansatsangi/isolate_handler.git
  path: ^1.9.0
  mime_type: ^1.0.0
  cherry_toast: ^1.10.0
  intl: ^0.19.0
  open_filex: ^4.4.0
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  isar: ^3.1.0+1
  isar_flutter_libs: 
    git: https://github.com/kumsumit/isar_flutter_libs.git  
  device_apps:
    git: https://github.com/sumitsharansatsangi/flutter_plugin_device_apps.git
  video_thumbnail:
    git: https://github.com/kumsumit/video_thumbnail.git
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  percent_indicator:
    git: https://github.com/diegoveloper/flutter_percent_indicator.git
  permission_handler:
    git: https://github.com/kumsumit/permission_handler.git
  riverpod_annotation: ^2.3.5
  flutter_native_splash: ^2.4.0
  share_plus:
    git: https://github.com/kumsumit/share_plus.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator:
    git: https://github.com/kumsumit/isar_generator.git
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
  
flutter_native_splash:
  color: "#129389"
  color_dark: "#129389"
  android: true
  ios: true
  image_android: android/app/src/main/ic_launcher-playstore.png
  image_dark_android: android/app/src/main/ic_launcher-playstore.png
  image_ios: android/app/src/main/ic_launcher-playstore.png
  image_dark_ios: android/app/src/main/ic_launcher-playstore.png
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: android/app/src/main/ic_launcher-playstore.png
    image_dark: android/app/src/main/ic_launcher-playstore.png
    color: "#129389"
    color_dark: "#129389"

 